# Generated by Django 3.1.7 on 2021-03-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210327_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_performer',
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignedOrderSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4)),
                ('assign_time', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.courier')),
                ('finished_orders', models.ManyToManyField(to='delivery.Order')),
                ('notstarted_orders', models.ManyToManyField(related_name='sets_with_notstarted_status', to='delivery.Order')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='current_set_of_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.assignedorderset'),
        ),
        migrations.AddField(
            model_name='order',
            name='set_of_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.assignedorderset'),
        ),
    ]
